### ISSUE TITLE
in javascript, doing ws.send("test") make the server crash for try_write

### ISSUE THREAD

**Issue by allan-simon** [nbaksalyar/rust-chat#2]
with the error  `repr: Os(32)`  (seems like a broken pipe error)

I know your blog post does not cover it, but I was wondering if you had a clue ?

**Comment by nbaksalyar** [comment]
Hi Allan!

Please let me know, what operating system are you using?

> I know your blog post does not cover it

Actually it will be covered in the next part, about bad effects of using `unwrap()` :)

**Comment by allan-simon** [comment]
I'm on ubuntu 14.10 (64 bits) ,  kernel 3.16

Is it because of the one shot flag we put ? i.e the socket get closed after that ?

**Comment by nbaksalyar** [comment]
The issue is fixed, now ws.send is handled correctly.

**Comment by allan-simon** [comment]
awesome, thanks
