### ISSUE TITLE
CPU usage skyrockets to 100% after a client disconnects

### ISSUE THREAD

**Issue by DamianX** [nbaksalyar/rust-chat#3]
Just `cargo run` and `nc localhost 10000`, hit CTRL-C, and voilà.
Sadly I'm a newbie so I don't have any idea what should be done to fix this

**Comment by allan-simon** [comment]
I a total newbie too, but as I was reading http://hermanradtke.com/2015/07/12/my-basic-understanding-of-mio-and-async-io.html 

> There are four types of events:
> 
>    readable - Tells the event loop we want to read data from a client connection.
>    writable - Tells the event loop we want to write data to a client connection.
>    hup - Tells the event loop that we want to be notified when a client closes the connection (hangs up).
>    error - Tells the event loop that we want to listen for errors.

so is it related to the fact there's no code related to hup ?

**Comment by nbaksalyar** [comment]
Closing the issue as now connection hangups are handled properly.
Please let me know if the problem persists.
