### ISSUE TITLE
Cargo build falling with error: the trait `core::marker::Sync` is not implemented for the type `core::cell::UnsafeCell<core::option::Option<usize>>` [E0277]

### ISSUE THREAD

**Issue by alpha6** [nbaksalyar/rust-chat#6]
Deniss-MacBook-Pro:rust-chat alpha6$ rustc --version
rustc 1.5.0 (3d7cd77e4 2015-12-04)

cargo --version
cargo 0.6.0-nightly (e1ed995 2015-10-22)

Mio version from Cargo.lock

[root]
name = "rust-chat"
version = "0.2.1"
dependencies = [
 "mio-websocket 0.1.0 (git+https://github.com/nbaksalyar/mio-websocket)",
]

Deniss-MacBook-Pro:rust-chat alpha6$ cargo build
    Updating git repository `https://github.com/nbaksalyar/mio-websocket`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/carllerche/mio`
   Compiling mio-websocket v0.1.0 (https://github.com/nbaksalyar/mio-websocket#22683c35)
/Users/alpha6/.cargo/git/checkouts/mio-websocket-d397e85029d5792d/master/src/interface.rs:39:9: 39:22 error: the trait `core::marker::Sync` is not implemented for the type `core::cell::UnsafeCell<core::option::Option<usize>>` [E0277]
/Users/alpha6/.cargo/git/checkouts/mio-websocket-d397e85029d5792d/master/src/interface.rs:39         thread::spawn(move || {

**Comment by nbaksalyar** [comment]
This should be fixed by now.
Thank you!
